server:
  port: 8989
spring:
  elasticsearch:
    uris:
      - http://10.111.43.55:9200
  datasource:
    username: root               #数据库的用户名
    password: mysql729          #数据库的密码
    url: jdbc:mysql://localhost:3306/onlineexam?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8    #url
    driver-class-name: com.mysql.cj.jdbc.Driver             #数据库的驱动
    hikari:
      minimum-idle: 5
      max-lifetime: 100
      maximum-pool-size: 30
      auto-commit: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  redis:
    database: 0             #redis 数据库索引（默认为0）
    host: 10.111.43.55      #redis 服务器地址
    port: 6379              #redis 服务器连接端口号
    password:               #redis 服务器连接密码  默认为空
    lettuce:
      pool:
        max-active: 8        # 连接池最大连接数(使用负值表示没有限制） 默认8
        max-wait: -1         #连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-idle: 8          #连接池最大空闲连接 默认8
        min-idle: 0          #连接池最小空闲连接 默认 0
    timeout: 3000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true                          #下划线转驼峰
  mapper-locations: classpath:/mapper/xml/*Mapper.xml
  type-aliases-package: com.onlineExam.pojo
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1

#Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug