spring:
  profiles:
    active: dev
mica:
  xss:
    enabled: true
# minio 参数配置
minio:
  endpoint: http://10.111.43.55:9000
  accessKey: admin
  secretKey: 12345678
  bucketName: file
#
#knife4j:
#  # 开启增强
##  enable: true
#  # 开启登录认证
#  basic:
#    enable: true
#    username: test
#    password: test

## 加密
#encrypt:
#  body:
#    aes-key: 1234567899165456
#    des-key: 123456789913545343453

