# 微信配置
wx:
  miniapp:
    configs:
      - appid: wx2b1b9f396a67b94c
        secret: #微信小程序的Secret
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
